build: false

skip_branch_with_pr: true

image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "6"
  NOW_TOKEN:
    secure: DF3YDyyn4Yrrc5EtFTht9oVVKdMkXTvp+Fi6gRpAV0c=

configuration: Release
platform:
  - x86
  - x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform;
  - node --version
  - npm --version
  - npm install

before_test:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))
  - ps: Set-ScreenResolution 1920 1080

test_script:
  - npm test

after_test:
  - if defined APPVEYOR_REPO_TAG_NAME (
      npm run rebuild &&
      7z a -ttar %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar ui.node &&
      7z a -tgzip %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar.gz %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar
    )

artifacts:
  - path: '**\*.tar.gz'

deploy:
  - provider: GitHub
    artifact: /.*\.gz/
    draft: false
    prerelease: true
    auth_token:
      secure: eMIAnmLDhZy2Sq/UAXB50fYr1C2BugaafN8XiV6Wur8wMvPLXWIuCKU7Jt/Y9Of6
    on:
      appveyor_repo_tag: true
      nodejs_version: "10"

on_finish:
  - cd tests\_snapshots
  - ..\..\node_modules\.bin\now --public --token %NOW_TOKEN%
